# Generated by Django 5.0.14 on 2026-06-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
    ]
