# Generated by Django 5.0.14 on 2026-06-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BGBCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('operational_status', models.CharField(choices=[('Active', 'Active / Operational'), ('Inactive', 'Temporarily Inactive')], default='Active', max_length=15)),
            ],
        ),
    ]
